// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: feeds.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createFeed = `-- name: CreateFeed :execresult
INSERT INTO feeds (id, user_id, name, url, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateFeedParams struct {
	ID        int64
	UserID    int64
	Name      string
	Url       string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFeed,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Url,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const getFeedByID = `-- name: GetFeedByID :one
SELECT id, user_id, name, url, created_at, updated_at, last_fetched_at FROM feeds WHERE id = ?
`

func (q *Queries) GetFeedByID(ctx context.Context, id int64) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByID, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastFetchedAt,
	)
	return i, err
}

const getFeeds = `-- name: GetFeeds :many
SELECT id, user_id, name, url, created_at, updated_at, last_fetched_at FROM feeds
`

func (q *Queries) GetFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextFeedsToFetch = `-- name: GetNextFeedsToFetch :many
SELECT id, user_id, name, url, created_at, updated_at, last_fetched_at FROM feeds ORDER BY last_fetched_at LIMIT ?
`

func (q *Queries) GetNextFeedsToFetch(ctx context.Context, limit int32) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getNextFeedsToFetch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFeedFetched = `-- name: MarkFeedFetched :execresult
UPDATE feeds
SET last_fetched_at = CURRENT_TIMESTAMP(), updated_at = CURRENT_TIMESTAMP()
WHERE id = ?
`

func (q *Queries) MarkFeedFetched(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, markFeedFetched, id)
}
