// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type Feed struct {
	ID            int64
	UserID        int64
	Name          string
	Url           string
	CreatedAt     time.Time
	UpdatedAt     sql.NullTime
	LastFetchedAt sql.NullTime
}

type FeedFollow struct {
	ID        int64
	UserID    int64
	FeedID    int64
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type Post struct {
	ID          int64
	FeedID      int64
	Title       string
	Description sql.NullString
	Url         string
	PublishedAt time.Time
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
}

type User struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	ApiKey    string
}
