// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: posts.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPost = `-- name: CreatePost :execresult
INSERT INTO posts (id, feed_id, title, description, url, published_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePostParams struct {
	ID          int64
	FeedID      int64
	Title       string
	Description sql.NullString
	Url         string
	PublishedAt time.Time
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPost,
		arg.ID,
		arg.FeedID,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.PublishedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const getPostsForUser = `-- name: GetPostsForUser :many
SELECT posts.id, posts.feed_id, posts.title, posts.description, posts.url, posts.published_at, posts.created_at, posts.updated_at from posts
JOIN feed_follows ON posts.feed_id = feed_follows.feed_id
WHERE feed_follows.user_id = ?
ORDER BY posts.published_at DESC
LIMIT ?
`

type GetPostsForUserParams struct {
	UserID int64
	Limit  int32
}

func (q *Queries) GetPostsForUser(ctx context.Context, arg GetPostsForUserParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
